addons:
  code_climate:
    repo_token: 24fff5bcb3f0f6c8150f809fed97b8dad2b37be25d0bab21cd14a73669199cfd
language: ruby
sudo: false
cache: bundler
services:
- mysql
rvm:
- 2.2.3
- 2.3.0
env:
- CI=1 DB=mysql
- CI=1 DB=postgres
matrix:
  exclude:
    - rvm: 2.2.3
      env: CI=1 DB=postgres
script:
- bundle exec rspec spec
before_script:
- sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database localizable_model_test;'; fi"
- sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database localizable_model_test' -U postgres; fi"
- bundle exec rake db:migrate
